# Generated by Django 2.1.11 on 2019-08-25 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=50, null=True)),
                ('uid', models.CharField(max_length=30, null=True)),
                ('total_reimbursements_made', models.IntegerField(default=0)),
                ('total_reimbursements_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=21)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('uuid', models.CharField(default=uuid.uuid1, max_length=64)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('uid', models.CharField(max_length=30, null=True)),
                ('yearly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_reimbursements_accepted', models.IntegerField(default=0)),
                ('total_reimbursements_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('total_purchases_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_reimbursements_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Recipient'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Store'),
        ),
    ]
